import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { getGlobalDataDir, registerStore } from '../../src/core/index.js';
import { ALL_WORKFLOWS, CORE_WORKFLOWS } from '../../src/core/profiles.js';
import { getSkillTemplates } from '../../src/core/shared/skill-generation.js';
import { createOpenSpecRoot } from '../helpers/openspec-fixtures.js';
import { runCLI } from '../helpers/run-cli.js';

describe('profile handoff CLI regressions (#1734)', () => {
  let tempDir: string;
  let project: string;
  let env: NodeJS.ProcessEnv;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'openspec-profile-handoffs-'));
    project = path.join(tempDir, 'project');
    await fs.mkdir(project);
    env = {
      XDG_CONFIG_HOME: path.join(tempDir, 'config'),
      XDG_DATA_HOME: path.join(tempDir, 'data'),
      USERPROFILE: path.join(tempDir, 'user-profile'), // Isolate global skill discovery (MiniMax).
    };
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  async function cli(args: string[]): Promise<string> {
    const result = await runCLI(args, { cwd: project, env });
    expect(result.exitCode, result.stderr || result.stdout).toBe(0);
    return result.stdout;
  }

  it.each(['skills', 'commands', 'both'])('keeps fresh and refreshed core %s free of optional handoffs', async (delivery) => {
    const configDir = path.join(env.XDG_CONFIG_HOME!, 'openspec');
    await fs.mkdir(configDir, { recursive: true });
    const configFile = path.join(configDir, 'config.json');
    await fs.writeFile(configFile, JSON.stringify({ profile: 'core', delivery }));
    await cli(['init', '--tools', 'claude', '--profile', 'core', '--no-animation', '--force']);

    const files = [
      ...(delivery !== 'commands' ? getSkillTemplates(CORE_WORKFLOWS).map(({ dirName }) =>
        path.join(project, '.claude', 'skills', dirName, 'SKILL.md')) : []),
      ...(delivery !== 'skills' ? CORE_WORKFLOWS.map(id =>
        path.join(project, '.claude', 'commands', 'opsx', `${id}.md`)) : []),
    ];
    async function assertCore(): Promise<void> {
      if (delivery !== 'commands') {
        expect((await fs.readdir(path.join(project, '.claude', 'skills'))).sort())
          .toEqual(getSkillTemplates(CORE_WORKFLOWS).map(entry => entry.dirName).sort());
      }
      if (delivery !== 'skills') {
        expect((await fs.readdir(path.join(project, '.claude', 'commands', 'opsx'))).sort())
          .toEqual(CORE_WORKFLOWS.map(id => `${id}.md`).sort());
      }
      for (const file of files) {
        const content = await fs.readFile(file, 'utf-8');
        expect(content, file).not.toMatch(/\/opsx:(continue|new)\b|openspec-(continue|new)-change/);
      }
    }
    await assertCore();

    // Simulate files generated by an older release, then use the normal refresh path.
    for (const file of files) {
      const old = (await fs.readFile(file, 'utf-8')).replace(/generatedBy: "[^"]+"/, 'generatedBy: "0.0.0"');
      await fs.writeFile(file, `${old}\nStale handoff: /opsx:continue\n`);
    }
    await cli(['update']);
    await assertCore();

    // Explicit opt-in still works; switching back removes the optional files.
    await fs.writeFile(configFile, JSON.stringify({ profile: 'custom', delivery, workflows: ALL_WORKFLOWS }));
    await cli(['update']);
    const continueFile = delivery === 'commands'
      ? path.join(project, '.claude', 'commands', 'opsx', 'continue.md')
      : path.join(project, '.claude', 'skills', 'openspec-continue-change', 'SKILL.md');
    expect(await fs.readFile(continueFile, 'utf-8')).toContain('Continue working on a change');
    await fs.writeFile(configFile, JSON.stringify({ profile: 'core', delivery }));
    await cli(['update']);
    await assertCore();
  }, 30_000);

  it.each(['local', 'store'])('supports the CLI recovery with custom artifact ids in a %s root', async (scope) => {
    const root = scope === 'store' ? path.join(tempDir, 'planning-store') : project;
    createOpenSpecRoot(root);
    const flags = scope === 'store' ? ['--store', 'planning'] : [];
    if (scope === 'store') {
      await registerStore({ id: 'planning', localPath: root, globalDataDir: getGlobalDataDir({ env }) });
      createOpenSpecRoot(project); // A local root must not steal the selected store's change.
    }
    const schemaDir = path.join(root, 'openspec', 'schemas', 'handoff-test');
    await fs.mkdir(path.join(schemaDir, 'templates'), { recursive: true });
    await fs.writeFile(path.join(schemaDir, 'schema.yaml'), `name: handoff-test
version: 1
artifacts:
  - id: brief
    generates: brief.md
    description: Planning brief
    template: brief.md
    instruction: Explain the intended behavior.
    requires: []
apply:
  requires: [brief]
  instruction: Implement the brief.
`);
    await fs.writeFile(path.join(schemaDir, 'templates', 'brief.md'), '# Brief\n');
    await fs.writeFile(path.join(root, 'openspec', 'config.yaml'), 'schema: handoff-test\ncontext: Preserve existing behavior.\nrules:\n  brief:\n    - Include a verification plan.\n');
    await cli(['new', 'change', 'original', ...flags]);
    const changeRoot = path.join(root, 'openspec', 'changes', 'original');
    const before = await fs.readdir(changeRoot);
    const blocked = JSON.parse(await cli(['instructions', 'apply', '--change', 'original', '--json', ...flags]));
    expect(blocked.state).toBe('blocked');
    expect(blocked.instruction).not.toContain('openspec-continue-change');
    expect(blocked.instruction).toContain(`openspec status --change original`);
    const blockedText = await cli(['instructions', 'apply', '--change', 'original', ...flags]);
    expect(blockedText).not.toContain('openspec-continue-change');
    const status = JSON.parse(await cli(['status', '--change', 'original', '--json', ...flags]));
    const next = status.artifacts.find((artifact: { status: string }) => artifact.status === 'ready');
    expect(next.id).toBe('brief');
    const instructions = JSON.parse(await cli(['instructions', next.id, '--change', 'original', '--json', ...flags]));
    expect(instructions.template).toBe('# Brief\n');
    expect(instructions.instruction).toBe('Explain the intended behavior.');
    expect(instructions.context).toBe('Preserve existing behavior.');
    expect(instructions.rules).toEqual(['Include a verification plan.']);
    expect(instructions.resolvedOutputPath).toBe(path.join(await fs.realpath(changeRoot), 'brief.md'));
    expect(await fs.readdir(changeRoot)).toEqual(before); // Status/instructions do not create artifacts.

    // A fixture write models the separate creation step, not an agent execution.
    await fs.writeFile(instructions.resolvedOutputPath, '# Brief\n\nConfirmed planning artifact.\n');
    const ready = JSON.parse(await cli(['instructions', 'apply', '--change', 'original', '--json', ...flags]));
    expect(ready.state).toBe('ready');
    await cli(['new', 'change', 'different-intent', ...flags]);
    expect(await fs.readFile(instructions.resolvedOutputPath, 'utf-8')).toBe('# Brief\n\nConfirmed planning artifact.\n');
    if (scope === 'store') {
      expect(await fs.readdir(path.join(project, 'openspec', 'changes'))).toEqual(['archive']);
    }
  }, 30_000);

  it.each([
    { name: 'missing', content: undefined, total: 0 },
    { name: 'empty', content: '# Work\n', total: 0 },
    { name: 'text-less checkboxes', content: '- [ ]\n', total: 1 },
  ])('repairs $name tracking without an optional workflow or a ready artifact', async ({ content, total }) => {
    createOpenSpecRoot(project);
    const schemaDir = path.join(project, 'openspec', 'schemas', 'tracking-test');
    await fs.mkdir(path.join(schemaDir, 'templates'), { recursive: true });
    await fs.writeFile(path.join(schemaDir, 'schema.yaml'), `name: tracking-test
version: 1
artifacts:
  - id: brief
    generates: brief.md
    description: Planning brief
    template: brief.md
    requires: []
apply:
  requires: [brief]
  tracks: implementation/checklist.md
`);
    await fs.writeFile(path.join(schemaDir, 'templates', 'brief.md'), '# Brief\n');
    await fs.writeFile(path.join(project, 'openspec', 'config.yaml'), 'schema: tracking-test\n');
    await cli(['new', 'change', 'tracking']);
    const changeRoot = path.join(project, 'openspec', 'changes', 'tracking');
    const briefPath = path.join(changeRoot, 'brief.md');
    await fs.writeFile(briefPath, '# Brief\n\nKeep this plan unchanged.\n');
    const trackingPath = path.join(changeRoot, 'implementation', 'checklist.md');
    await fs.mkdir(path.dirname(trackingPath));
    if (content !== undefined) await fs.writeFile(trackingPath, content);

    const status = JSON.parse(await cli(['status', '--change', 'tracking', '--json']));
    expect(status.artifacts.map((artifact: { status: string }) => artifact.status)).toEqual(['done']);
    const blocked = JSON.parse(await cli(['instructions', 'apply', '--change', 'tracking', '--json']));
    expect(blocked.state).toBe('blocked');
    expect(blocked.missingArtifacts).toBeUndefined();
    expect(blocked.progress).toEqual({ total, complete: 0, remaining: total });
    expect(blocked.tasks).toEqual([]);
    expect(blocked.instruction).not.toContain('openspec-continue-change');
    expect(blocked.instruction).toContain('checklist.md');
    expect(blocked.instruction).toContain('openspec status --change tracking');
    expect(await cli(['instructions', 'apply', '--change', 'tracking'])).not.toContain('openspec-continue-change');
    if (content === undefined) {
      await expect(fs.stat(trackingPath)).rejects.toMatchObject({ code: 'ENOENT' });
    } else {
      expect(await fs.readFile(trackingPath, 'utf-8')).toBe(content);
    }

    // The fixture repairs tracking separately; CLI status/progress semantics stay unchanged.
    await fs.writeFile(trackingPath, '- [ ] Implement the brief\n');
    const ready = JSON.parse(await cli(['instructions', 'apply', '--change', 'tracking', '--json']));
    expect(ready.state).toBe('ready');
    expect(ready.progress).toEqual({ total: 1, complete: 0, remaining: 1 });
    await fs.writeFile(trackingPath, '- [x] Implement the brief\n');
    const done = JSON.parse(await cli(['instructions', 'apply', '--change', 'tracking', '--json']));
    expect(done.state).toBe('all_done');
    expect(done.progress).toEqual({ total: 1, complete: 1, remaining: 0 });
    expect(await fs.readFile(briefPath, 'utf-8')).toBe('# Brief\n\nKeep this plan unchanged.\n');
  }, 30_000);
});
