import { describe, expect, it } from 'vitest';

import {
  getSkillTemplates,
  getCommandContents,
  generateSkillContent,
} from '../../../src/core/shared/skill-generation.js';
import {
  ALL_WORKFLOWS,
  CORE_WORKFLOWS,
  getProfileWorkflows,
} from '../../../src/core/profiles.js';
import { transformToSkillReferences } from '../../../src/utils/command-references.js';

/**
 * Nothing OpenSpec generates may name a workflow the installation does not
 * have. The reference resolves to a skill that was never written, so the agent
 * is sent somewhere it cannot go and the flow dead-ends (#1734, umbrella #919).
 *
 * The default `core` profile is the case that shipped broken, but arbitrary
 * subsets are reachable too: a `custom` profile is whatever workflows the user
 * picked, and `openspec update` re-derives a set from what it finds on disk
 * (legacy tool overrides, inferred Codex workflows) without passing it through
 * getProfileWorkflows. So assert the property over a family of subsets rather
 * than over one profile.
 *
 * Assertions run on the generated bytes, in both spellings: the canonical
 * `/opsx:<id>` a command file carries and the `/openspec-<skill>` a skills-only
 * install carries.
 */
const skillNameFor = (id: string) => transformToSkillReferences(`/opsx:${id}`);

/**
 * Every subset that could expose a reference:
 * - each workflow alone: nothing may name anything but itself;
 * - everything but one: catches a reference hidden inside another workflow's
 *   installed branch;
 * - the empty set: catches a reference hidden in a *fallback* branch;
 * - the two shipped profiles.
 */
const SUBSETS: Array<[string, readonly string[]]> = [
  ['core profile', getProfileWorkflows('core')],
  ['every workflow', ALL_WORKFLOWS],
  ['no workflows', []],
  ...ALL_WORKFLOWS.map(
    (id) => [`only ${id}`, [id]] as [string, readonly string[]]
  ),
  ...ALL_WORKFLOWS.map(
    (id) =>
      [`every workflow but ${id}`, ALL_WORKFLOWS.filter((w) => w !== id)] as [
        string,
        readonly string[],
      ]
  ),
];

describe('generated files never name an uninstalled workflow', () => {
  it('covers the core profile and every single-workflow-difference subset', () => {
    expect([...getProfileWorkflows('core')].sort()).toEqual([...CORE_WORKFLOWS].sort());
    expect(SUBSETS).toHaveLength(3 + ALL_WORKFLOWS.length * 2);
  });

  it.each(SUBSETS)('holds for the skills generated with %s', (_label, workflows) => {
    const installed = new Set<string>(workflows);
    const absent = ALL_WORKFLOWS.filter((id) => !installed.has(id));

    for (const { template, dirName } of getSkillTemplates(workflows)) {
      const content = generateSkillContent(template, 'TEST');
      const skillsOnly = transformToSkillReferences(content);

      for (const id of absent) {
        expect(content, `${dirName} -> /opsx:${id}`).not.toContain(`/opsx:${id}`);
        expect(skillsOnly, `${dirName} -> ${skillNameFor(id)}`).not.toContain(
          skillNameFor(id)
        );
      }
    }
  });

  it.each(SUBSETS)('holds for the commands generated with %s', (_label, workflows) => {
    const installed = new Set<string>(workflows);
    const absent = ALL_WORKFLOWS.filter((id) => !installed.has(id));

    for (const { id: commandId, body } of getCommandContents(workflows)) {
      for (const id of absent) {
        expect(body, `${commandId} -> /opsx:${id}`).not.toContain(`/opsx:${id}`);
      }
    }
  });

  // The mirror image: dropping a reference must not drop the handoff itself.
  // With every workflow installed, every reference that exists is emitted.
  // `bulk-archive` is the one workflow nothing points at - it is reached from
  // the CLI, not from another workflow.
  it('still names every referenced workflow when the profile installs them', () => {
    const bodies = [
      ...getSkillTemplates(ALL_WORKFLOWS).map(
        ({ dirName, template }) => [dirName, template.instructions] as const
      ),
      ...getCommandContents(ALL_WORKFLOWS).map(({ id, body }) => [id, body] as const),
    ];
    const named = new Set<string>();

    for (const [, body] of bodies) {
      for (const id of ALL_WORKFLOWS) {
        if (body.includes(`/opsx:${id}`)) named.add(id);
      }
    }

    expect([...named].sort()).toEqual(
      [...ALL_WORKFLOWS].filter((id) => id !== 'bulk-archive').sort()
    );
  });

  // Archiving merges delta specs into main specs, which is the sync workflow's
  // job. Selecting archive in a custom profile pulls sync in with it.
  it('injects sync for a custom profile that selects archive', () => {
    expect(getProfileWorkflows('custom', ['archive'])).toContain('sync');
    expect(getProfileWorkflows('custom', ['bulk-archive'])).toContain('sync');
  });
});
