import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  findApplyTracksWarning,
  parseSchema,
  SchemaValidationError,
} from '../../../src/core/artifact-graph/schema.js';
import { cliProjectRoot } from '../../helpers/run-cli.js';

/**
 * `parseSchema` checked `artifacts[].requires` but never the `apply` block, so
 * a typo there passed `openspec schema validate` and failed silently at run
 * time: an unknown `apply.requires` id was skipped, turning off the apply gate,
 * and an unmatched `apply.tracks` blocked apply for good.
 */
const ARTIFACTS = `
name: test
version: 1
artifacts:
  - id: proposal
    generates: proposal.md
    description: Proposal
    template: proposal.md
  - id: design
    generates: design.md
    description: Design
    template: design.md
    requires: [proposal]
  - id: tasks
    generates: tasks.md
    description: Tasks
    template: tasks.md
    requires: [proposal]
  - id: checklist
    generates: "work/*.md"
    description: Checklist
    template: checklist.md
    requires: [proposal]
`;

const withApply = (apply: string) => `${ARTIFACTS}apply:\n${apply}\n`;

function errorFrom(yaml: string): Error {
  try {
    parseSchema(yaml);
  } catch (error) {
    return error as Error;
  }
  throw new Error('expected parseSchema to throw');
}

describe('parseSchema apply references', () => {
  describe('apply.requires', () => {
    it('accepts ids the schema declares', () => {
      const schema = parseSchema(withApply('  requires: [design, tasks]\n  tracks: tasks.md'));
      expect(schema.apply?.requires).toEqual(['design', 'tasks']);
    });

    it('rejects an id no artifact declares, naming it and the declared ids', () => {
      const error = errorFrom(withApply('  requires: [desgin]'));
      expect(error).toBeInstanceOf(SchemaValidationError);
      expect(error.message).toContain(`Invalid apply.requires reference: 'desgin' does not exist`);
      expect(error.message).toContain('proposal, design, tasks, checklist');
    });

    it('rejects one unknown id among valid ones', () => {
      const error = errorFrom(withApply('  requires: [design, tsks]\n  tracks: tasks.md'));
      expect(error).toBeInstanceOf(SchemaValidationError);
      expect(error.message).toContain(`'tsks' does not exist`);
    });

    it('is case-sensitive, like artifact requires', () => {
      expect(() => parseSchema(withApply('  requires: [Tasks]'))).toThrow(
        /Invalid apply\.requires reference: 'Tasks'/
      );
    });
  });

  describe('apply.tracks', () => {
    it('accepts the generates path of a declared artifact', () => {
      const schema = parseSchema(withApply('  requires: [tasks]\n  tracks: tasks.md'));
      expect(schema.apply?.tracks).toBe('tasks.md');
    });

    it('accepts a glob generates repeated verbatim', () => {
      const schema = parseSchema(withApply('  requires: [checklist]\n  tracks: "work/*.md"'));
      expect(schema.apply?.tracks).toBe('work/*.md');
    });

    it('accepts an apply block that tracks nothing', () => {
      expect(() => parseSchema(withApply('  requires: [tasks]'))).not.toThrow();
      expect(() => parseSchema(withApply('  requires: [tasks]\n  tracks: null'))).not.toThrow();
    });

    // Apply reads `tracks` as a path, so a schema whose `tracks` value matches
    // no `generates` value exactly works today. Failing the load would break
    // every command on it; `schema validate` warns instead.
    it('still loads a path no artifact generates, and warns about it', () => {
      const schema = parseSchema(withApply('  requires: [tasks]\n  tracks: task.md'));
      const warning = findApplyTracksWarning(schema);
      expect(warning).toContain(
        `apply.tracks 'task.md' does not exactly match any artifact's generates value`
      );
      expect(warning).toContain('tasks.md');
      expect(warning).toContain('Make apply.tracks exactly equal one of those generates values');
    });

    it('still loads a single file that only matches a glob generates, and warns', () => {
      const schema = parseSchema(withApply('  requires: [checklist]\n  tracks: work/todo.md'));
      const warning = findApplyTracksWarning(schema);
      expect(warning).toContain(`'work/todo.md'`);
      // The glob `work/*.md` really does generate `work/todo.md`, so the
      // warning must describe the string mismatch, never claim the file is
      // ungenerated.
      expect(warning).toContain(`does not exactly match any artifact's generates value`);
      expect(warning).not.toContain('is not generated by any artifact');
    });

    it('does not warn when tracks names a generates path, or nothing', () => {
      expect(findApplyTracksWarning(parseSchema(withApply('  requires: [tasks]\n  tracks: tasks.md')))).toBeUndefined();
      expect(findApplyTracksWarning(parseSchema(withApply('  requires: [checklist]\n  tracks: "work/*.md"')))).toBeUndefined();
      expect(findApplyTracksWarning(parseSchema(withApply('  requires: [tasks]')))).toBeUndefined();
      expect(findApplyTracksWarning(parseSchema(ARTIFACTS))).toBeUndefined();
    });

    // The tracked-tasks lookup compares `tracks` and `generates` as plain
    // strings, so a Windows separator on one side and a POSIX one on the other
    // is a mismatch the warning must report, not a match it normalizes away.
    describe('Windows path separators', () => {
      const WINDOWS_ARTIFACTS = `
name: test
version: 1
artifacts:
  - id: tasks
    generates: 'tasks\\main.md'
    description: Tasks
    template: tasks.md
`;
      const windowsApply = (tracks: string) =>
        `${WINDOWS_ARTIFACTS}apply:\n  requires: [tasks]\n  tracks: '${tracks}'\n`;

      it('warns when tracks uses a backslash but generates uses a forward slash', () => {
        const schema = parseSchema(withApply(`  requires: [checklist]\n  tracks: 'work\\*.md'`));
        expect(schema.apply?.tracks).toBe('work\\*.md');
        expect(findApplyTracksWarning(schema)).toContain(
          `apply.tracks 'work\\*.md' does not exactly match any artifact's generates value`
        );
      });

      it('warns when generates uses a backslash but tracks uses a forward slash', () => {
        const schema = parseSchema(windowsApply('tasks/main.md'));
        expect(schema.artifacts[0].generates).toBe('tasks\\main.md');
        expect(findApplyTracksWarning(schema)).toContain(
          `apply.tracks 'tasks/main.md' does not exactly match any artifact's generates value`
        );
      });

      it('does not warn when tracks and generates spell the same backslash path', () => {
        expect(findApplyTracksWarning(parseSchema(windowsApply('tasks\\main.md')))).toBeUndefined();
      });
    });
  });

  it('accepts a schema with no apply block', () => {
    expect(parseSchema(ARTIFACTS).apply).toBeUndefined();
  });

  it('still parses every built-in schema', () => {
    const schemasDir = path.join(cliProjectRoot, 'schemas');
    const names = fs
      .readdirSync(schemasDir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name);
    expect(names.length).toBeGreaterThan(0);
    for (const name of names) {
      const yaml = fs.readFileSync(path.join(schemasDir, name, 'schema.yaml'), 'utf-8');
      expect(() => parseSchema(yaml), name).not.toThrow();
    }
  });
});
